version: 2
updates:
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /crypto/rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /mobile
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dart-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      container-images:
        patterns:
          - "*"
