[package]
name = "private_messenger_crypto"
version = "0.1.0"
edition = "2021"
rust-version = "1.90"
license = "AGPL-3.0-or-later"
publish = false

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[profile.release]
panic = "unwind"
overflow-checks = true

[dependencies]
aes-gcm = "=0.11.1"
openmls = { version = "=0.9.0", default-features = false }
openmls_basic_credential = "=0.6.0"
openmls_rust_crypto = "=0.6.0"
openmls_traits = "=0.6.0"
sha2 = "=0.11.0"
tls_codec = "=0.4.2"
